services:
  - type: web
    name: i-love-text
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /api/health
    pullRequestPreviewsEnabled: false
